name: Build Argon 2.4.3 (Flint2)

on:
  workflow_dispatch:

env:
  TZ: Europe/Warsaw
  SDK_URL: https://downloads.openwrt.org/releases/24.10.2/targets/mediatek/filogic/openwrt-sdk-24.10.2-mediatek-filogic_gcc-13.3.0_musl.Linux-x86_64.tar.zst
  ARGON_REPO: https://github.com/jerrykuku/luci-theme-argon.git
  ARGON_TAG: v2.4.3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare
        run: |
          sudo apt-get update -y
          sudo apt-get install -y zstd build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-venv rsync unzip zlib1g-dev file wget

      - name: Download OpenWrt SDK (mediatek/filogic, 24.10.2)
        run: |
          wget -O sdk.tar.zst "$SDK_URL"
          mkdir sdk && tar --zstd -xvf sdk.tar.zst -C ./sdk --strip-components=1

      - name: Configure feeds for OpenWrt 24.10
        working-directory: sdk
        run: |
          cat > feeds.conf << 'EOF'
          src-git-full packages https://github.com/openwrt/packages.git;openwrt-24.10
          src-git-full luci https://github.com/openwrt/luci.git;openwrt-24.10
          src-git-full routing https://git.openwrt.org/feed/routing.git;openwrt-24.10
          EOF
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Add luci-theme-argon (tag v2.4.3)
        working-directory: sdk
        run: |
          mkdir -p package/external
          git clone --branch "$ARGON_TAG" --depth 1 "$ARGON_REPO" package/external/luci-theme-argon

      - name: Prepare .config
        working-directory: sdk
        run: |
          # minimalny config + nasze zależności
          cat > .config << 'EOF'
          CONFIG_ALL_NONSHARED=n
          CONFIG_ALL_KMODS=n
          CONFIG_ALL=n
          CONFIG_AUTOREMOVE=n
          CONFIG_LUCI_LANG_pl=y

          # argon jako moduł (ipk)
          CONFIG_PACKAGE_luci-theme-argon=m

          # kluczowe zależności do zbudowania lucihttp:
          CONFIG_PACKAGE_liblua5.1=y
          CONFIG_PACKAGE_lua5.1=y
          CONFIG_PACKAGE_libucode=y
          CONFIG_PACKAGE_ucode=y

          # dobrym pomysłem jest też mieć luci-base (ściągnie pełne zależności LuCI)
          CONFIG_PACKAGE_luci-base=y
          EOF

          make defconfig


      - name: Download sources
        working-directory: sdk
        run: make package/luci-theme-argon/download -j$(nproc) V=s

      - name: Compile
        working-directory: sdk
        run: make package/luci-theme-argon/{clean,compile} -j$(nproc) V=s

      - name: Collect IPKs
        working-directory: sdk
        run: |
          mkdir -p ../out
          find bin -name 'luci-theme-argon*_aarch64_cortex-a53.ipk' -exec cp {} ../out/ \;
          ls -l ../out

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: luci-theme-argon_2.4.3_aarch64_cortex-a53
          path: out/*.ipk
          if-no-files-found: error

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v2.4.3-flint2
          name: luci-theme-argon 2.4.3 (Flint2 / aarch64_cortex-a53)
          files: out/*.ipk
          generate_release_notes: true
